#!/usr/bin/env python3
"""
Figure out the correct mapping from garbled chars to real box chars.

The garbled chars in the file are: É, æ, û, ê, ò, ù, ö, ¥, Ü, Γ
These should be box/block drawing chars.

Strategy: looking at the LOGO pattern visually, deduce the mapping.
The LOGO displays as "PALADIN" in block art, using chars like:
  █ (full block)  
  ╔╗╚╝║═ (box drawing)

From looking at the garbled banner screenshot:
  Γûê = should be █ (full block U+2588) 
  Γòù = should be ╗ (U+2557) or similar
  Γòö = should be ╠ 
  Γòæ = should be ║ (vertical)
  Γò¥ = should be ╝
  ΓòÉ = should be ═ 
  Γòö = ...
  
Actually the simplest approach: look at the raw bytes in the file and 
decode them as cp437 to see if that recovers the block chars.

The file bytes for Γûê (U+0393 U+00FB U+00EA) are: CE 93 C3 BB C3 AA
These 6 bytes don't produce anything useful when re-decoded as cp437.

BUT: the original source of the file might have been a cp437 terminal where
█ = 0xDB. When saved/converted: 
  0xDB in cp437 = █  
  0xDB as a single byte in a UTF-8 file is invalid (it's > 0x7F)
  So the tool that created the file might have:
    - Read 0xDB as cp1252 char 'Û' (U+00DB)
    - Saved that as UTF-8: C3 9B
  
  C3 9B as UTF-8 = U+00DB = Û  
  But the file has CE 93 (Γ) C3 BB (û) C3 AA (ê)...
  
  CE 93 = U+0393 (Γ)
  This CANNOT come from a single latin-1 byte since U+0393 > U+00FF.
  
  UNLESS the file was saved by first writing byte 0x93 raw,
  then later "fixed" by a BOM-aware tool that re-read it as UTF-8:
  
  Byte sequence: 93 FB EA  
  Not valid UTF-8! The tool would replace 0x93 with U+FFFD (replacement char)?
  No — unless it decoded as cp1252 first:
    0x93 in cp1252 = U+201C = " (left double quotation mark)
    0xFB in cp1252 = U+00FB = û
    0xEA in cp1252 = U+00EA = ê
  Then THAT string was re-encoded as UTF-8: E2 80 9C C3 BB C3 AA
  But that gives 6 bytes, and U+201C ("), U+00FB (û), U+00EA (ê)...
  Still not what we see (U+0393).

The only codec I know where 0x93 maps to U+0393 is if someone used
the wrong codec. Let me systematically test all Python codecs.
"""
import sys, encodings.aliases
sys.stdout.reconfigure(encoding='utf-8')

target_char = chr(0x0393)  # Γ

print(f"Searching for codec where byte 0x93 -> U+0393 ({target_char}):")
all_encodings = set(encodings.aliases.aliases.values())
matches = []
for enc in sorted(all_encodings):
    try:
        ch = bytes([0x93]).decode(enc)
        if ch == target_char:
            matches.append(enc)
    except:
        pass

if matches:
    for m in matches:
        print(f"  Found: {m}")
else:
    print("  None found!")

print()

# Different approach: what if the file was generated by a Python script that
# just used the block chars directly, and the file is CORRECT UTF-8,
# but we need to just force the terminal to use UTF-8?
# 
# Let's check what U+0393 actually renders as in the context of the logo.
# Looking at the original screenshot more carefully:
# The logo shows: ΓûêΓûêΓûêΓûêΓûêΓûêΓòù  ΓûêΓûêΓûêΓûêΓûêΓòù
# This looks like block letters P-A-L-A-D-I-N
#
# "Γûê" appears many times - it's the "solid" block character = █
# "Γòù" appears at corners/ends
# 
# If the Windows console receives these as UTF-8 bytes and displays with cp1252:
# █ U+2588 -> UTF-8: E2 96 88
#   0xE2 in cp1252 = â
#   0x96 in cp1252 = – (en dash)  
#   0x88 in cp1252 = ˆ (combining circumflex)
#   Display: â–ˆ which is NOT Γûê

# ╔ U+2554 -> UTF-8: E2 95 94
#   0xE2 = â, 0x95 = … (ellipsis?), 0x94 = " (right low quotation)
#   Not Γòù either

# So the chars are NOT normal block/box chars rendered through cp1252.
# They must be SOMETHING ELSE.

# Let me look at this differently:
# Γ (U+0393) + û (U+00FB) + ê (U+00EA) 
# In UTF-8 bytes: CE 93 C3 BB C3 AA
# 
# What if these 3 chars encode a SINGLE character when treated as 
# Modified UTF-8 / CESU-8 or some other variant?
# 
# Actually: CE 93 = correct UTF-8 for U+0393.
# But what if the original file used "REPLACEMENT CHARACTERS" where
# each 3-char group maps to one visual glyph?
#
# OR: the source was in "LATIN EXTENDED" encoding where these specific
# code points ARE block chars in some font?
# 
# I think the answer is simpler: the file as-is IS correct, but the
# terminal (Windows cmd/PowerShell with cp1252 codepage) can't render
# these Unicode characters properly because:
# 1. The terminal's active codepage is not UTF-8 (chcp 65001)
# 2. The font doesn't support these characters
#
# The chars Γûê, Γòù etc. ARE the rendering of block chars in a cp1252 terminal!
# Let me verify:
# When Python does print("█") on Windows cp1252 console:
#   Python outputs UTF-8 bytes E2 96 88
#   Windows console (cp1252) interprets E2=â, 96=SYN control?, 88=ˆ
# That gives "â" + control char + "ˆ" which is "âˆ"... not Γûê

# HOWEVER, in Python 3, print() on Windows uses the console's encoding.
# If stdout is in cp1252 mode, Python will try to encode the char as cp1252.
# █ (U+2588) is NOT in cp1252, so Python raises UnicodeEncodeError.
# UNLESS errors='replace', in which case it becomes '?'.

# So the actual rendering of Γûê means the terminal IS receiving some chars
# that it maps to Γûê through its own font/rendering.

# THE ANSWER: The chars in the file ARE the correct visual chars,
# but they're UNICODE box drawing chars that Windows renders differently
# depending on the terminal app.
# The screenshot shows garbled text because the terminal theme/font doesn't
# support those specific Unicode points.
# The solution: use ANSI-compatible chars or ensure UTF-8 codepage.

print("Summary: The file content is correct UTF-8 Unicode.")
print("The garbled display is a WINDOWS TERMINAL CODEPAGE issue.")
print("Fix: add 'chcp 65001' before running, or use sys.stdout.reconfigure(encoding='utf-8')")
print()

# Final verification: what are the actual Unicode names?
test_chars = [chr(0x0393), chr(0x00FB), chr(0x00EA), chr(0x00F2), 
              chr(0x00F9), chr(0x00DC), chr(0x00C9), chr(0x00E6)]
import unicodedata
print("Characters in file (first few unique ones):")
for ch in test_chars:
    print(f"  U+{ord(ch):04X} ({ch}) = {unicodedata.name(ch)}")
