#!/usr/bin/env python3
"""
paladin — AI security agent for your terminal.
Interactive REPL that delegates all work to kiro-cli with full tool trust.
"""

import os, sys, shutil, subprocess, json, platform, re, threading
from pathlib import Path
from datetime import datetime

# ── Rich (optional, for richer input prompts) ────────────────────────────────
try:
    from rich.prompt import Prompt as RPrompt
    HAS_RICH = True
except ImportError:
    HAS_RICH = False

# ─────────────────────────────────────────────────────────────────────────────
VERSION      = "0.1.0"
CONFIG_DIR   = Path.home() / ".paladin"
CONFIG_FILE  = CONFIG_DIR / "config.json"
HISTORY_FILE = CONFIG_DIR / "history"
SESSION_FILE = CONFIG_DIR / "session.json"
DEFAULTS     = {"model": None, "agent": "paladin"}

# Locate kiro binary — try all known names
KIRO_BIN = (
    shutil.which("kiro-cli-chat")
    or shutil.which("kiro")
    or shutil.which("kiro-cli")
)

# Absolute path to this script's directory — used for --working-dir and agent config
SCRIPT_DIR = Path(__file__).resolve().parent

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Bootstrap — writes agent config + hook script on every startup
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

COMMANDS_LOG = str(SCRIPT_DIR / "commands.log")
HOOK_SCRIPT  = str(Path.home() / ".kiro" / "hooks" / "paladin-log-command.py")
AGENT_CONFIG = str(Path.home() / ".kiro" / "agents" / "paladin.json")

HOOK_SCRIPT_CONTENT = '''\
#!/usr/bin/env python3
"""
paladin-log-command.py  —  auto-generated by paladin.py
postToolUse hook: logs every shell command kiro runs + its output.
"""

import json, os, sys
from datetime import datetime

event      = json.load(sys.stdin)
tool       = event.get("tool_name", "")
tool_input = event.get("tool_input", {})
tool_resp  = event.get("tool_response", {})
cwd        = event.get("cwd", "")

if tool not in ("shell", "execute_bash", "execute_cmd"):
    sys.exit(0)

command     = tool_input.get("command", "")
working_dir = tool_input.get("working_dir") or cwd
session_id  = os.environ.get("KIRO_SESSION_ID", "unknown")
ts          = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

stdout = stderr = exit_status = ""
results = tool_resp.get("result", [])
if results and isinstance(results, list):
    stdout      = results[0].get("stdout", "").strip()
    stderr      = results[0].get("stderr", "").strip()
    exit_status = results[0].get("exit_status", "")

log_path = "{log_path}"

with open(log_path, "a") as f:
    f.write(f"[{{ts}}] session={{session_id}}\\n")
    f.write(f"  cwd:    {{working_dir}}\\n")
    f.write(f"  cmd:    {{command}}\\n")
    f.write(f"  exit:   {{exit_status}}\\n")
    if stdout:
        f.write(f"  output:\\n")
        for line in stdout.splitlines():
            f.write(f"    {{line}}\\n")
    if stderr:
        f.write(f"  stderr:\\n")
        for line in stderr.splitlines():
            f.write(f"    {{line}}\\n")
    f.write("\\n")

sys.exit(0)
'''

def bootstrap():
    """
    Called once at startup. Writes:
      - ~/.kiro/hooks/paladin-log-command.py   (hook script)
      - ~/.kiro/agents/paladin.json            (agent config)
    Overwrites both so they're always in sync with this version of paladin.
    """
    # ── hook script ──────────────────────────────────────────────────────────
    hook_dir = Path(HOOK_SCRIPT).parent
    hook_dir.mkdir(parents=True, exist_ok=True)

    hook_src = HOOK_SCRIPT_CONTENT.replace("{log_path}", COMMANDS_LOG)
    Path(HOOK_SCRIPT).write_text(hook_src)
    Path(HOOK_SCRIPT).chmod(0o755)

    # ── agent config ─────────────────────────────────────────────────────────
    agent_dir = Path(AGENT_CONFIG).parent
    agent_dir.mkdir(parents=True, exist_ok=True)

    agent_cfg = {
        "name": "paladin",
        "description": "Paladin AI security agent — full tool access, auto-approved, logs all shell commands",
        "prompt": (
            "You are Paladin, an AI security agent running in the terminal. "
            "You have full access to filesystem, shell, and web tools. "
            "RULES: "
            "1) When the user asks you to run a command, list files, create/edit files, "
            "or anything requiring a tool — USE THE TOOL, never just describe what to do. "
            "2) You have shell, read, write, grep, glob, and code tools — always use them. "
            "3) Never say you cannot write files or run commands. "
            "4) Execute tasks directly with your tools."
        ),
        "tools": ["shell", "read", "write", "grep", "glob", "code", "web_search", "web_fetch"],
        "allowedTools": ["shell", "read", "write", "grep", "glob", "code", "web_search", "web_fetch"],
        "toolsSettings": {
            "shell": {
                "autoAllowReadonly": True
            }
        },
        "hooks": {
            "postToolUse": [
                {
                    "matcher": "shell",
                    "command": f"python3 {HOOK_SCRIPT}"
                }
            ]
        }
    }

    Path(AGENT_CONFIG).write_text(json.dumps(agent_cfg, indent=2))


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# ANSI palette
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

R     = "\033[0m"
B     = "\033[1m"
DIM   = "\033[2m"
IT    = "\033[3m"
UL    = "\033[4m"

CY    = "\033[38;5;39m"    # bright sky-blue
CY2   = "\033[38;5;80m"    # lighter cyan
GR    = "\033[38;5;78m"    # soft green
YL    = "\033[38;5;221m"   # warm yellow
RD    = "\033[38;5;203m"   # soft red
MA    = "\033[38;5;171m"   # purple/magenta
OR    = "\033[38;5;215m"   # orange
WH    = "\033[38;5;253m"   # off-white
GREY  = "\033[38;5;243m"   # mid grey
LGREY = "\033[38;5;238m"   # dark grey (borders)

BG_CODE = "\033[48;5;235m"  # code block bg

CYB   = f"{B}{CY}"

def _W() -> int:
    try:    return max(60, os.get_terminal_size().columns - 4)
    except: return 80

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Config / session helpers
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _mkdirs():
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

def load_config() -> dict:
    if not CONFIG_FILE.exists(): return dict(DEFAULTS)
    try:
        with open(CONFIG_FILE) as f: return {**DEFAULTS, **json.load(f)}
    except Exception: return dict(DEFAULTS)

def save_config(cfg: dict):
    _mkdirs()
    with open(CONFIG_FILE, "w") as f: json.dump(cfg, f, indent=2)

def load_session() -> dict:
    if not SESSION_FILE.exists(): return {}
    try:
        with open(SESSION_FILE) as f: return json.load(f)
    except Exception: return {}

def save_session(data: dict):
    _mkdirs()
    with open(SESSION_FILE, "w") as f: json.dump(data, f, indent=2)

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Box / rendering helpers
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _ansi_len(s: str) -> int:
    return len(re.sub(r"\x1b\[[0-9;]*m", "", s))

def _center(text: str, width: int) -> str:
    vlen = _ansi_len(text)
    pad  = max(0, width - vlen)
    return " " * (pad // 2) + text + " " * (pad - pad // 2)

def _wrap_text(text: str, width: int) -> list:
    import textwrap
    raw = re.sub(r"\x1b\[[0-9;]*m", "", text)
    if len(raw) <= width: return [text]
    return textwrap.wrap(raw, width) or [raw]

def _box_top(inner: int, title: str = "") -> str:
    if title:
        tlen  = _ansi_len(title)
        left  = max(1, (inner - tlen) // 2)
        right = max(1, inner - tlen - left)
        return f"{LGREY}╭{'─'*left}{title}{LGREY}{'─'*right}╮{R}"
    return f"{LGREY}╭{'─'*inner}╮{R}"

def _box_row(content: str, inner: int) -> str:
    pad = max(0, inner - _ansi_len(content) - 2)
    return f"{LGREY}│{R} {content}{' '*pad} {LGREY}│{R}"

def _box_sep(inner: int) -> str:
    return f"{LGREY}├{'─'*inner}┤{R}"

def _box_bot(inner: int) -> str:
    return f"{LGREY}╰{'─'*inner}╯{R}"

def _print_box(title: str, lines: list, title_color: str = None):
    """Print a titled info box to stdout."""
    inner = _W() - 2
    tc    = title_color or CYB
    print(_box_top(inner, title=f" {tc}{title}{R} "))
    for line in lines:
        print(_box_row(line, inner))
    print(_box_bot(inner))

def _ok(msg: str):   print(f"  {GR}✓{R}  {WH}{msg}{R}")
def _err(msg: str):  print(f"  {RD}✗{R}  {WH}{msg}{R}")
def _warn(msg: str): print(f"  {YL}◆{R}  {WH}{msg}{R}")
def _info(msg: str): print(f"  {CY2}›{R}  {GREY}{msg}{R}")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Markdown-lite renderer (for streaming kiro output)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

_in_code = False

def _inline(t: str) -> str:
    t = re.sub(r"`([^`]+)`",      lambda m: f"{BG_CODE}{YL} {m.group(1)} {R}", t)
    t = re.sub(r"\*\*(.+?)\*\*",  lambda m: f"{B}{WH}{m.group(1)}{R}",         t)
    t = re.sub(r"\*(.+?)\*",      lambda m: f"{IT}{GREY}{m.group(1)}{R}",       t)
    t = re.sub(r"__(.*?)__",      lambda m: f"{UL}{m.group(1)}{R}",             t)
    return t

def _render_and_print(raw: str, inner: int = 0):
    """
    Render one line of kiro output with light markdown styling.
    If inner > 0, wrap the line inside box borders.
    """
    global _in_code
    line = raw.rstrip("\n")
    w    = inner or (_W() - 2)

    def emit(text: str):
        if inner:
            print(_box_row(text, inner))
        else:
            print(text)

    # fenced code block
    if line.startswith("```"):
        if not _in_code:
            _in_code = True
            lang = line[3:].strip() or "text"
            emit(f"  {BG_CODE}{LGREY}┌── {CY2}{lang}{LGREY}{'─'*max(1,36-len(lang))}┐{R}")
        else:
            _in_code = False
            emit(f"  {BG_CODE}{LGREY}└{'─'*38}┘{R}")
        return
    if _in_code:
        emit(f"  {BG_CODE}{GR}{line}{R}")
        return
    if not line.strip():
        emit("")
        return

    # headings
    m = re.match(r"^(#{1,3}) (.*)", line)
    if m:
        lvl, txt = len(m.group(1)), m.group(2)
        if lvl == 1:
            emit(f"")
            emit(f"  {CYB}{txt}{R}")
            emit(f"  {CY}{'═'*min(len(txt)+2,50)}{R}")
            emit(f"")
        elif lvl == 2:
            emit(f"")
            emit(f"  {B}{WH}{txt}{R}")
            emit(f"  {LGREY}{'─'*min(len(txt)+2,40)}{R}")
        else:
            emit(f"  {B}{GREY}{txt}{R}")
        return

    # horizontal rule
    if re.match(r"^[-*_]{3,}$", line.strip()):
        emit(f"  {LGREY}{'─'*min(w-4,60)}{R}")
        return

    # bullet
    m = re.match(r"^(\s*)([-*•]) (.*)", line)
    if m:
        depth  = len(m.group(1)) // 2
        indent = "    " * depth
        icons  = [f"{CY}◆{R}", f"{CY2}◇{R}", f"{GREY}·{R}"]
        emit(f"  {indent}{icons[min(depth,2)]} {_inline(m.group(3))}")
        return

    # numbered list
    m = re.match(r"^(\s*)(\d+)\. (.*)", line)
    if m:
        depth  = len(m.group(1)) // 2
        indent = "    " * depth
        emit(f"  {indent}{CY}{m.group(2)}.{R} {_inline(m.group(3))}")
        return

    # blockquote
    if line.startswith(">"):
        emit(f"  {CY}▎{R}{IT}{GREY} {line[1:].strip()}{R}")
        return

    # table
    if line.startswith("|") and line.endswith("|"):
        cells = [c.strip() for c in line.strip("|").split("|")]
        row   = f"  {LGREY}│{R}"
        for c in cells:
            if re.match(r"^[-: ]+$", c):
                row += f" {LGREY}{'─'*max(len(c),3)}{R} {LGREY}│{R}"
            else:
                row += f" {_inline(c)} {LGREY}│{R}"
        emit(row)
        return

    emit(f"  {_inline(line)}")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Kiro bridge — the core
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def ask_kiro(prompt: str, label: str = "kiro", model: str = None,
             cwd: str = None, trust: bool = True):
    """
    Print a 'you' bubble, send prompt to kiro-cli, stream response inside a
    matching '⬡ paladin' box so everything looks consistent.
    """
    global _in_code
    _in_code = False

    inner = _W() - 2
    ts    = datetime.now().strftime("%H:%M")

    # ── user bubble ──────────────────────────────────────────────────────────
    print()
    print(_box_top(inner, title=f" {GR}▸ you{R} "))
    import textwrap as _tw
    for part in prompt.splitlines():
        for chunk in (_tw.wrap(part, inner - 4) or [part]):
            print(_box_row(f"{WH}{chunk}{R}", inner))
    ts_pad = inner - len(ts) - 2
    print(_box_row(f"{' '*ts_pad}{LGREY}{ts}{R}", inner))
    print(_box_bot(inner))

    if not KIRO_BIN:
        print()
        print(_box_top(inner, title=f" {CYB}⬡ paladin{R} "))
        print(_box_row(f"{RD}✗{R}  kiro-cli not found — install from https://kiro.ai", inner))
        print(_box_bot(inner))
        print()
        return

    # ── paladin response box: open it, stream inside, close it ───────────────
    work_dir = cwd or str(Path.cwd())
    ts2      = datetime.now().strftime("%H:%M:%S")
    sess_id  = load_session().get("id", "")
    tag      = f"  {LGREY}#{sess_id[-5:]}{R}" if sess_id else ""
    sub      = f"{DIM}{label}{R}{tag}  {LGREY}{ts2}{R}"

    print()
    print(_box_top(inner, title=f" {CYB}⬡ paladin{R} "))
    print(_box_row(_center(sub, inner - 2), inner))
    print(_box_sep(inner))

    cmd = [KIRO_BIN, "chat", "--no-interactive", "--agent", "paladin", prompt]
    if trust:
        cmd.append("--trust-all-tools")
    if model:
        cmd += ["--model", model]

    start = datetime.now().timestamp()
    got   = False

    try:
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
            cwd=work_dir,
        )
        for raw in proc.stdout:
            got = True
            _render_and_print(raw, inner)
        proc.wait()
        if proc.returncode not in (0, None) and not got:
            print(_box_row(f"{YL}◆{R}  kiro exited with code {proc.returncode}", inner))
    except KeyboardInterrupt:
        print(_box_row(f"{DIM}interrupted{R}", inner))
        print(_box_bot(inner))
        print()
        return
    except Exception as e:
        print(_box_row(f"{RD}✗{R}  {e}", inner))
        print(_box_bot(inner))
        print()
        return

    if not got:
        print(_box_row(f"{YL}◆{R}  No response received from kiro.", inner))

    elapsed = datetime.now().timestamp() - start
    print()
    print(_box_row(f"{DIM}⏱  {elapsed:.1f}s{R}", inner))
    print(_box_bot(inner))
    print()

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Banner
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

LOGO = [
    " ██████╗  █████╗ ██╗      █████╗ ██████╗ ██╗███╗   ██╗",
    " ██╔══██╗██╔══██╗██║     ██╔══██╗██╔══██╗██║████╗  ██║",
    " ██████╔╝███████║██║     ███████║██║  ██║██║██╔██╗ ██║",
    " ██╔═══╝ ██╔══██║██║     ██╔══██║██║  ██║██║██║╚██╗██║",
    " ██║     ██║  ██║███████╗██║  ██║██████╔╝██║██║ ╚████║",
    " ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═════╝ ╚═╝╚═╝  ╚═══╝",
]

def print_banner():
    inner = _W() - 2
    sess  = load_session()
    sid   = sess.get("id", "")
    stat  = sess.get("status", "idle")
    proj  = sess.get("project", "")

    kiro_str = (f"{GR}⬤  kiro connected{R}" if KIRO_BIN
                else f"{RD}○  kiro not found{R}  {LGREY}→ https://kiro.ai{R}")
    sc       = {"running": GR, "paused": YL, "failed": RD, "idle": LGREY}.get(stat, LGREY)
    sess_str = (f"{LGREY}session  {R}{CYB}{sid}{R}  {LGREY}{proj}  {R}{sc}● {stat}{R}"
                if sid else f"{LGREY}no session  ·  type {R}{CY}start{R}{LGREY} to begin{R}")
    shortcuts = f"{DIM}/help · /clear · /session · /model <name> · exit{R}"

    print()
    print(_box_top(inner, title=f" {CYB}⬡ paladin{R} "))
    for ll in LOGO:
        print(_box_row(_center(f"{CY}{ll}{R}", inner - 2), inner))
    print(_box_row(_center(f"{DIM}AI Security Agent · v{VERSION} · powered by kiro{R}", inner - 2), inner))
    print(_box_sep(inner))
    print(_box_row(_center(kiro_str,  inner - 2), inner))
    print(_box_row(_center(sess_str,  inner - 2), inner))
    print(_box_sep(inner))
    print(_box_row(_center(shortcuts, inner - 2), inner))
    print(_box_bot(inner))
    print()


def print_help():
    sections = [
        ("Session", [
            ("init",           "Initialise paladin in current project"),
            ("start",          "Start a new agent session"),
            ("status",         "Show session status"),
            ("run [task]",     "Run any task via kiro (with full tool access)"),
        ]),
        ("Approvals", [
            ("approvals",      "List pending approvals"),
            ("approve <id>",   "Approve an action"),
            ("deny <id>",      "Deny an action"),
        ]),
        ("Activity & Policy", [
            ("activity [id]",  "Show activity log"),
            ("policy list",    "List security policies"),
            ("policy add",     "Add a policy interactively"),
            ("policy test",    "Test a prompt against policies"),
        ]),
        ("Utilities", [
            ("config",         "Show / edit config"),
            ("doctor",         "Health check"),
            ("version",        "Version info"),
        ]),
        ("REPL shortcuts", [
            ("/help",          "Show this help"),
            ("/clear",         "Clear screen"),
            ("/session",       "Show session details"),
            ("/model <name>",  "Switch model"),
            ("exit / Ctrl-C",  "Quit"),
        ]),
    ]
    print()
    for group, items in sections:
        print(f"  {B}{GREY}{group}{R}")
        for cmd, desc in items:
            pad = max(1, 22 - len(cmd))
            print(f"    {CY}{cmd}{R}{' '*pad}{GREY}{desc}{R}")
        print()

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Commands
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _ask_input(label: str, choices: list = None, default: str = "") -> str:
    sfx = f" [{'/'.join(choices)}]" if choices else (f" [{default}]" if default else "")
    try:
        raw = input(f"\n  {label}{sfx}: ").strip()
    except (EOFError, KeyboardInterrupt):
        return default
    return raw or default


def cmd_init(model: str = None):
    cwd    = Path.cwd()
    marker = cwd / ".paladin"
    if marker.exists():
        _warn(".paladin already exists — re-initializing.")
    marker.write_text(json.dumps({
        "initialized_at": datetime.now().isoformat(),
        "project": cwd.name,
    }, indent=2))
    _ok(f"Initialized paladin in {cwd}")
    ask_kiro(
        f"I have initialized the Paladin AI security agent in the project at: {cwd}. "
        "The project is called '{cwd.name}'. Briefly acknowledge and list what you can "
        "monitor and protect in this project.",
        label="init", model=model, cwd=str(cwd),
    )


def cmd_start(model: str = None):
    sid = f"SES-{int(datetime.now().timestamp())}"
    save_session({
        "id": sid,
        "started_at": datetime.now().isoformat(),
        "status": "running",
        "project": Path.cwd().name,
    })
    _ok(f"Session {CYB}{sid}{R} started")
    ask_kiro(
        f"A new Paladin security session has started. Session ID: {sid}. "
        "Project: {Path.cwd().name}. Greet the user and ask what they want to work on.",
        label="start", model=model,
    )


def cmd_status(model: str = None):
    sess = load_session()
    if not sess:
        _warn("No active session. Run: start")
        return
    print()
    _print_box("Session Status", [
        f"{GREY}{'id':<16}{R}{CY2}{sess.get('id','')}{R}",
        f"{GREY}{'project':<16}{R}{CY2}{sess.get('project','')}{R}",
        f"{GREY}{'started':<16}{R}{CY2}{sess.get('started_at','')}{R}",
        f"{GREY}{'status':<16}{R}{GR}{sess.get('status','')}{R}",
    ])
    ask_kiro(
        f"Summarize this Paladin session: {json.dumps(sess)}. "
        "What is happening, are there any pending actions or risks?",
        label="status", model=model,
    )


def cmd_run(task: str = None, model: str = None):
    if not task:
        task = _ask_input("Task to run")
    if not task:
        _err("No task provided.")
        return
    sess = load_session()
    ctx  = f"\n\nCurrent session: {json.dumps(sess)}" if sess else ""
    # Pass the task directly — no wrapper verbiage so kiro treats it as a real task
    ask_kiro(task + ctx, label="run", model=model, trust=True)


def cmd_approvals(model: str = None):
    ask_kiro(
        "List all pending Paladin approval requests. "
        "For each: ID, tool name, risk level (low/medium/high/critical), and a brief description.",
        label="approvals", model=model,
    )


def cmd_approve(aid: str, msg: str = None, model: str = None):
    note = f" Additional note: {msg}" if msg else ""
    ask_kiro(
        f"Approve Paladin action ID: {aid}.{note} Confirm the approval and proceed with execution.",
        label=f"approve {aid}", model=model,
    )


def cmd_deny(aid: str, msg: str = None, model: str = None):
    note = f" Reason: {msg}" if msg else ""
    ask_kiro(
        f"Deny Paladin action ID: {aid}.{note} Confirm the denial and explain why.",
        label=f"deny {aid}", model=model,
    )


def cmd_activity(sid: str = None, model: str = None):
    if sid:
        ask_kiro(
            f"Show the full activity log for Paladin session {sid}. "
            "Include all tool calls, agent messages, shield decisions, and user approvals in order.",
            label=f"activity {sid}", model=model,
        )
    else:
        ask_kiro(
            "Show the activity log for the current Paladin session. "
            "Include tool calls, agent messages, shield decisions, and user approvals.",
            label="activity", model=model,
        )


def cmd_policy_list(model: str = None):
    ask_kiro(
        "List all Paladin security policies. For each: name, action (allow/ask/block), "
        "risk threshold, enabled status, and description.",
        label="policy list", model=model,
    )


def cmd_policy_add(model: str = None):
    name    = _ask_input("Policy name")
    desc    = _ask_input("Description")
    action  = _ask_input("Action", choices=["allow", "ask", "block"], default="ask")
    thresh  = _ask_input("Risk threshold (0–100)", default="50")
    pattern = _ask_input("Match pattern (optional, press Enter to skip)")
    pol: dict = {
        "name": name,
        "description": desc,
        "action": action,
        "threshold": int(thresh or 50),
        "enabled": True,
    }
    if pattern:
        pol["match_patterns"] = [pattern]
    ask_kiro(
        f"Add this Paladin security policy: {json.dumps(pol)}. "
        "Confirm it has been added and explain when it will trigger.",
        label="policy add", model=model,
    )


def cmd_policy_test(model: str = None):
    ti = _ask_input("Prompt or tool call to test")
    if not ti:
        _err("Nothing to test.")
        return
    ask_kiro(
        f'Test the following against all Paladin security policies: "{ti}". '
        "Show which policies match, the final decision, risk score, and reasoning.",
        label="policy test", model=model,
    )


def cmd_config():
    cfg = load_config()
    print()
    _print_box("Config", [
        f"{GREY}{'file':<16}{R}{DIM}{CONFIG_FILE}{R}",
        *[
            f"{GREY}{k:<16}{R}{CY2}{v}{R}" if v is not None
            else f"{GREY}{k:<16}{R}{LGREY}not set{R}"
            for k, v in cfg.items()
        ],
    ])
    try:
        edit = input("  Edit a value? (y/N): ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        return
    if edit == "y":
        key = _ask_input("Key")
        val = _ask_input(f"Value for {key}")
        cfg[key] = val
        save_config(cfg)
        _ok(f"{key} = {val}")


def cmd_doctor():
    checks = [
        ("kiro-cli",       bool(KIRO_BIN),              KIRO_BIN or "not found — https://kiro.ai"),
        ("python",         sys.version_info >= (3, 9),  platform.python_version()),
        ("rich",           HAS_RICH,                    "ok" if HAS_RICH else "pip install rich"),
        ("config dir",     CONFIG_DIR.exists(),          str(CONFIG_DIR)),
        (".paladin marker",(Path.cwd() / ".paladin").exists(),
                           "found" if (Path.cwd() / ".paladin").exists() else "run: init"),
        ("agent config",   (SCRIPT_DIR / ".kiro" / "agents" / "paladin.json").exists(),
                           "found" if (SCRIPT_DIR / ".kiro" / "agents" / "paladin.json").exists()
                           else "missing — hooks not active"),
    ]
    print()
    _print_box("paladin doctor", [
        f"{'  ' if good else '  '}{GR if good else YL}{'✓' if good else '◆'}{R}  "
        f"{B}{name:<20}{R}{GREY}{detail}{R}"
        for name, good, detail in checks
    ])


def cmd_version():
    print()
    _print_box("paladin version", [
        f"{GREY}{'version':<16}{R}{CYB}v{VERSION}{R}",
        f"{GREY}{'python':<16}{R}{CY2}{platform.python_version()}{R}",
        f"{GREY}{'platform':<16}{R}{CY2}{platform.system()} {platform.release()}{R}",
        f"{GREY}{'kiro':<16}{R}{(GR + KIRO_BIN + R) if KIRO_BIN else (RD + 'not found' + R)}",
    ])

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# REPL slash commands
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _handle_slash(line: str, model_ref: list):
    parts = line.strip().split()
    cmd   = parts[0].lower()

    if cmd in ("/exit", "/quit", "/q"):
        raise SystemExit(0)

    elif cmd == "/help":
        print_help()

    elif cmd == "/clear":
        os.system("clear")
        print_banner()

    elif cmd == "/session":
        s = load_session()
        if not s:
            _warn("No active session.")
            return
        print()
        for k, v in s.items():
            print(f"  {GREY}{k:<18}{R}{CY2}{v}{R}")
        print()

    elif cmd == "/model":
        if len(parts) > 1:
            model_ref[0] = parts[1]
            cfg = load_config()
            cfg["model"] = parts[1]
            save_config(cfg)
            _ok(f"Model → {B}{parts[1]}{R}")
        else:
            _info(f"Model: {B}{model_ref[0] or 'default (set by kiro)'}{R}")

    else:
        _err(f"Unknown slash command: {cmd}  (try /help)")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Dispatcher — maps text tokens to commands
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def _dispatch(args: list, model: str = None) -> bool:
    """Return True if args matched a built-in command, False if it should go to kiro."""
    if not args:
        return False
    cmd, rest = args[0].lower(), args[1:]

    if   cmd == "init":      cmd_init(model)
    elif cmd == "start":     cmd_start(model)
    elif cmd == "status":    cmd_status(model)
    elif cmd == "run":       cmd_run(" ".join(rest) if rest else None, model)
    elif cmd == "approvals": cmd_approvals(model)
    elif cmd == "approve":
        if not rest: _err("Usage: approve <id> [message]")
        else:        cmd_approve(rest[0], " ".join(rest[1:]) or None, model)
    elif cmd == "deny":
        if not rest: _err("Usage: deny <id> [reason]")
        else:        cmd_deny(rest[0], " ".join(rest[1:]) or None, model)
    elif cmd == "activity":  cmd_activity(rest[0] if rest else None, model)
    elif cmd == "policy":
        sub = rest[0].lower() if rest else ""
        if   sub == "list": cmd_policy_list(model)
        elif sub == "add":  cmd_policy_add(model)
        elif sub == "test": cmd_policy_test(model)
        else: _err("Usage: policy [list|add|test]")
    elif cmd == "config":    cmd_config()
    elif cmd == "doctor":    cmd_doctor()
    elif cmd == "version":   cmd_version()
    elif cmd in ("help", "--help", "-h"): print_help()
    else:
        return False
    return True

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Entry point
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def main():
    _mkdirs()
    bootstrap()  # always write agent config + hook script on startup
    args = sys.argv[1:]
    cfg  = load_config()
    model_ref = [cfg.get("model")]

    # ── one-shot mode: python paladin.py "do something" ──────────────────────
    if args:
        if not _dispatch(args, model_ref[0]):
            # Not a built-in command — pass the whole thing to kiro as a task
            ask_kiro(" ".join(args), label="task", model=model_ref[0], trust=True)
        return

    # ── interactive REPL ─────────────────────────────────────────────────────
    print_banner()

    # Warn if kiro is missing before we start
    if not KIRO_BIN:
        _err("kiro-cli not found. Install from https://kiro.ai and run `kiro login`.")
        print()

    try:
        while True:
            try:
                sess  = load_session()
                sid   = sess.get("id", "")
                tag   = f"#{sid[-5:]} " if sid else ""
                line  = input(f"  {CY}⬡ {tag}❯ {R}").strip()
            except EOFError:
                break
            except KeyboardInterrupt:
                print()
                break

            if not line:
                continue

            if line.lower() in ("exit", "quit", "q"):
                break

            if line.startswith("/"):
                _handle_slash(line, model_ref)
                continue

            tokens = line.split()
            if not _dispatch(tokens, model_ref[0]):
                # Free-form prompt — send directly to kiro with full tool trust
                ask_kiro(line, label="chat", model=model_ref[0], trust=True)

    except SystemExit:
        pass

    print(f"\n  {DIM}bye.{R}\n")


if __name__ == "__main__":
    main()
