#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
paladin -- AI security agent for your terminal.
Interactive REPL that delegates all work to kiro-cli with full tool trust.
"""

import os, sys, shutil, subprocess, json, platform, re
from pathlib import Path
from datetime import datetime

try:
    from rich.prompt import Prompt as RPrompt
    HAS_RICH = True
except ImportError:
    HAS_RICH = False

VERSION      = "0.1.0"
CONFIG_DIR   = Path.home() / ".paladin"
CONFIG_FILE  = CONFIG_DIR / "config.json"
SESSION_FILE = CONFIG_DIR / "session.json"
DEFAULTS     = {"model": None, "agent": "paladin"}

KIRO_BIN = (
    shutil.which("kiro-cli-chat")
    or shutil.which("kiro")
    or shutil.which("kiro-cli")
)

SCRIPT_DIR = Path(__file__).resolve().parent

# force stdout to utf-8 so box chars always render correctly
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

# ─── ANSI palette ─────────────────────────────────────────────────────────────

R     = "\033[0m"
B     = "\033[1m"
DIM   = "\033[2m"
IT    = "\033[3m"
UL    = "\033[4m"

CY    = "\033[38;5;39m"
CY2   = "\033[38;5;80m"
GR    = "\033[38;5;78m"
YL    = "\033[38;5;221m"
RD    = "\033[38;5;203m"
WH    = "\033[38;5;253m"
GREY  = "\033[38;5;243m"
LGREY = "\033[38;5;238m"

BG_CODE = "\033[48;5;235m"
CYB     = f"{B}{CY}"

def _W() -> int:
    try:    return max(60, os.get_terminal_size().columns - 4)
    except: return 80

# ─── Bootstrap ────────────────────────────────────────────────────────────────

COMMANDS_LOG = str(SCRIPT_DIR / "commands.log")
HOOK_SCRIPT  = str(Path.home() / ".kiro" / "hooks" / "paladin-log-command.py")
AGENT_CONFIG = str(Path.home() / ".kiro" / "agents" / "paladin.json")

HOOK_SCRIPT_CONTENT = '''\
#!/usr/bin/env python3
"""paladin-log-command.py -- auto-generated by paladin.py"""
import json, os, sys
from datetime import datetime

event      = json.load(sys.stdin)
tool       = event.get("tool_name", "")
tool_input = event.get("tool_input", {})
tool_resp  = event.get("tool_response", {})
cwd        = event.get("cwd", "")

if tool not in ("shell", "execute_bash", "execute_cmd"):
    sys.exit(0)

command     = tool_input.get("command", "")
working_dir = tool_input.get("working_dir") or cwd
session_id  = os.environ.get("KIRO_SESSION_ID", "unknown")
ts          = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

stdout = stderr = exit_status = ""
results = tool_resp.get("result", [])
if results and isinstance(results, list):
    stdout      = results[0].get("stdout", "").strip()
    stderr      = results[0].get("stderr", "").strip()
    exit_status = results[0].get("exit_status", "")

log_path = "{log_path}"

with open(log_path, "a") as f:
    f.write(f"[{{ts}}] session={{session_id}}\\n")
    f.write(f"  cwd:    {{working_dir}}\\n")
    f.write(f"  cmd:    {{command}}\\n")
    f.write(f"  exit:   {{exit_status}}\\n")
    if stdout:
        f.write("  output:\\n")
        for line in stdout.splitlines():
            f.write(f"    {{line}}\\n")
    if stderr:
        f.write("  stderr:\\n")
        for line in stderr.splitlines():
            f.write(f"    {{line}}\\n")
    f.write("\\n")

sys.exit(0)
'''

def bootstrap():
    hook_dir = Path(HOOK_SCRIPT).parent
    hook_dir.mkdir(parents=True, exist_ok=True)
    Path(HOOK_SCRIPT).write_text(
        HOOK_SCRIPT_CONTENT.replace("{log_path}", COMMANDS_LOG),
        encoding="utf-8",
    )
    Path(HOOK_SCRIPT).chmod(0o755)

    agent_dir = Path(AGENT_CONFIG).parent
    agent_dir.mkdir(parents=True, exist_ok=True)
    agent_cfg = {
        "name": "paladin",
        "description": "Paladin AI security agent -- full tool access, logs all shell commands",
        "prompt": (
            "You are Paladin, an AI security agent running in the terminal. "
            "You have full access to filesystem, shell, and web tools. "
            "RULES: 1) When the user asks you to run a command, list files, "
            "create/edit files, or anything requiring a tool -- USE THE TOOL, "
            "never just describe what to do. "
            "2) You have shell, read, write, grep, glob, and code tools -- always use them. "
            "3) Never say you cannot write files or run commands. "
            "4) Execute tasks directly with your tools."
        ),
        "tools": ["shell", "read", "write", "grep", "glob", "code", "web_search", "web_fetch"],
        "allowedTools": ["shell", "read", "write", "grep", "glob", "code", "web_search", "web_fetch"],
        "toolsSettings": {"shell": {"autoAllowReadonly": True}},
        "hooks": {
            "postToolUse": [
                {"matcher": "shell", "command": f"python3 {HOOK_SCRIPT}"}
            ]
        },
    }
    Path(AGENT_CONFIG).write_text(json.dumps(agent_cfg, indent=2), encoding="utf-8")

# ─── Config / session ─────────────────────────────────────────────────────────

def _mkdirs():
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)

def load_config() -> dict:
    if not CONFIG_FILE.exists(): return dict(DEFAULTS)
    try:
        with open(CONFIG_FILE, encoding="utf-8") as f: return {**DEFAULTS, **json.load(f)}
    except Exception: return dict(DEFAULTS)

def save_config(cfg: dict):
    _mkdirs()
    with open(CONFIG_FILE, "w", encoding="utf-8") as f: json.dump(cfg, f, indent=2)

def load_session() -> dict:
    if not SESSION_FILE.exists(): return {}
    try:
        with open(SESSION_FILE, encoding="utf-8") as f: return json.load(f)
    except Exception: return {}

def save_session(data: dict):
    _mkdirs()
    with open(SESSION_FILE, "w", encoding="utf-8") as f: json.dump(data, f, indent=2)

# ─── Box helpers ──────────────────────────────────────────────────────────────

def _ansi_len(s: str) -> int:
    return len(re.sub(r"\x1b\[[0-9;]*m", "", s))

def _center(text: str, width: int) -> str:
    pad = max(0, width - _ansi_len(text))
    return " " * (pad // 2) + text + " " * (pad - pad // 2)

def _wrap(text: str, width: int) -> list:
    import textwrap
    raw = re.sub(r"\x1b\[[0-9;]*m", "", text)
    if len(raw) <= width: return [text]
    return textwrap.wrap(raw, width) or [raw]

def _box_top(inner: int, title: str = "") -> str:
    if title:
        tlen  = _ansi_len(title)
        left  = max(1, (inner - tlen) // 2)
        right = max(1, inner - tlen - left)
        return f"{LGREY}\u256d{'\u2500'*left}{title}{LGREY}{'\u2500'*right}\u256e{R}"
    return f"{LGREY}\u256d{'\u2500'*inner}\u256e{R}"

def _box_row(content: str, inner: int) -> str:
    pad = max(0, inner - _ansi_len(content) - 2)
    return f"{LGREY}\u2502{R} {content}{' '*pad} {LGREY}\u2502{R}"

def _box_sep(inner: int) -> str:
    return f"{LGREY}\u251c{'\u2500'*inner}\u2524{R}"

def _box_bot(inner: int) -> str:
    return f"{LGREY}\u2570{'\u2500'*inner}\u256f{R}"

def _print_box(title: str, lines: list, title_color: str = None):
    inner = _W() - 2
    tc    = title_color or CYB
    print(_box_top(inner, title=f" {tc}{title}{R} "))
    for line in lines:
        print(_box_row(line, inner))
    print(_box_bot(inner))

def _ok(msg: str):   print(f"  {GR}\u2713{R}  {WH}{msg}{R}")
def _err(msg: str):  print(f"  {RD}\u2717{R}  {WH}{msg}{R}")
def _warn(msg: str): print(f"  {YL}\u25c6{R}  {WH}{msg}{R}")
def _info(msg: str): print(f"  {CY2}\u203a{R}  {GREY}{msg}{R}")

# ─── Markdown renderer ────────────────────────────────────────────────────────

_in_code = False

def _inline(t: str) -> str:
    t = re.sub(r"`([^`]+)`",     lambda m: f"{BG_CODE}{YL} {m.group(1)} {R}", t)
    t = re.sub(r"\*\*(.+?)\*\*", lambda m: f"{B}{WH}{m.group(1)}{R}",         t)
    t = re.sub(r"\*(.+?)\*",     lambda m: f"{IT}{GREY}{m.group(1)}{R}",       t)
    return t

def _render_and_print(raw: str, inner: int = 0):
    global _in_code
    line = raw.rstrip("\n")
    w    = inner or (_W() - 2)

    def emit(text: str):
        if inner: print(_box_row(text, inner))
        else:     print(text)

    if line.startswith("```"):
        if not _in_code:
            _in_code = True
            lang = line[3:].strip() or "text"
            emit(f"  {BG_CODE}{LGREY}\u250c\u2500\u2500 {CY2}{lang}{LGREY}{'\u2500'*max(1,36-len(lang))}\u2510{R}")
        else:
            _in_code = False
            emit(f"  {BG_CODE}{LGREY}\u2514{'\u2500'*38}\u2518{R}")
        return
    if _in_code:
        emit(f"  {BG_CODE}{GR}{line}{R}")
        return
    if not line.strip():
        emit(""); return

    m = re.match(r"^(#{1,3}) (.*)", line)
    if m:
        lvl, txt = len(m.group(1)), m.group(2)
        if lvl == 1:
            emit(""); emit(f"  {CYB}{txt}{R}"); emit(f"  {CY}{'='*min(len(txt)+2,50)}{R}"); emit("")
        elif lvl == 2:
            emit(""); emit(f"  {B}{WH}{txt}{R}"); emit(f"  {LGREY}{'-'*min(len(txt)+2,40)}{R}")
        else:
            emit(f"  {B}{GREY}{txt}{R}")
        return

    if re.match(r"^[-*_]{3,}$", line.strip()):
        emit(f"  {LGREY}{'-'*min(w-4,60)}{R}"); return

    m = re.match(r"^(\s*)([-*]) (.*)", line)
    if m:
        depth  = len(m.group(1)) // 2
        icons  = [f"{CY}\u25c6{R}", f"{CY2}\u25c7{R}", f"{GREY}\u00b7{R}"]
        emit(f"  {'    '*depth}{icons[min(depth,2)]} {_inline(m.group(3))}"); return

    m = re.match(r"^(\s*)(\d+)\. (.*)", line)
    if m:
        depth = len(m.group(1)) // 2
        emit(f"  {'    '*depth}{CY}{m.group(2)}.{R} {_inline(m.group(3))}"); return

    if line.startswith(">"):
        emit(f"  {CY}\u2596{R}{IT}{GREY} {line[1:].strip()}{R}"); return

    emit(f"  {_inline(line)}")

# ─── Kiro bridge ──────────────────────────────────────────────────────────────

def ask_kiro(prompt: str, label: str = "kiro", model: str = None,
             cwd: str = None, trust: bool = True):
    global _in_code
    _in_code = False

    inner = _W() - 2
    ts    = datetime.now().strftime("%H:%M")

    # user bubble
    print()
    print(_box_top(inner, title=f" {GR}\u25b8 you{R} "))
    import textwrap as _tw
    for part in prompt.splitlines():
        for chunk in (_tw.wrap(part, inner - 4) or [part]):
            print(_box_row(f"{WH}{chunk}{R}", inner))
    print(_box_row(f"{' '*(inner - len(ts) - 2)}{LGREY}{ts}{R}", inner))
    print(_box_bot(inner))

    if not KIRO_BIN:
        print()
        print(_box_top(inner, title=f" {CYB}\u2b21 paladin{R} "))
        print(_box_row(f"{RD}\u2717{R}  kiro-cli not found -- install from https://kiro.ai", inner))
        print(_box_bot(inner))
        print()
        return

    work_dir = cwd or str(Path.cwd())
    ts2      = datetime.now().strftime("%H:%M:%S")
    sess_id  = load_session().get("id", "")
    tag      = f"  {LGREY}#{sess_id[-5:]}{R}" if sess_id else ""
    sub      = f"{DIM}{label}{R}{tag}  {LGREY}{ts2}{R}"

    print()
    print(_box_top(inner, title=f" {CYB}\u2b21 paladin{R} "))
    print(_box_row(_center(sub, inner - 2), inner))
    print(_box_sep(inner))

    cmd = [KIRO_BIN, "chat", "--no-interactive", "--agent", "paladin", prompt]
    if trust: cmd.append("--trust-all-tools")
    if model: cmd += ["--model", model]

    start = datetime.now().timestamp()
    got   = False

    try:
        proc = subprocess.Popen(
            cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            text=True, bufsize=1, cwd=work_dir,
            env={**os.environ, "PYTHONIOENCODING": "utf-8"},
        )
        for raw in proc.stdout:
            got = True
            _render_and_print(raw, inner)
        proc.wait()
        if proc.returncode not in (0, None) and not got:
            print(_box_row(f"{YL}\u25c6{R}  kiro exited with code {proc.returncode}", inner))
    except KeyboardInterrupt:
        print(_box_row(f"{DIM}interrupted{R}", inner))
        print(_box_bot(inner)); print(); return
    except Exception as e:
        print(_box_row(f"{RD}\u2717{R}  {e}", inner))
        print(_box_bot(inner)); print(); return

    if not got:
        print(_box_row(f"{YL}\u25c6{R}  No response from kiro.", inner))

    elapsed = datetime.now().timestamp() - start
    print()
    print(_box_row(f"{DIM}\u23f1  {elapsed:.1f}s{R}", inner))
    print(_box_bot(inner))
    print()

# ─── Banner ───────────────────────────────────────────────────────────────────

LOGO = [
    " \u2588\u2588\u2588\u2588\u2588\u2588\u2557  \u2588\u2588\u2588\u2588\u2588\u2557 \u2588\u2588\u2557      \u2588\u2588\u2588\u2588\u2588\u2557 \u2588\u2588\u2588\u2588\u2588\u2588\u2557 \u2588\u2588\u2557\u2588\u2588\u2588\u2557   \u2588\u2588\u2557",
    " \u2588\u2588\u2554\u2550\u2550\u2588\u2588\u2557\u2588\u2588\u2554\u2550\u2550\u2588\u2588\u2557\u2588\u2588\u2551     \u2588\u2588\u2554\u2550\u2550\u2588\u2588\u2557\u2588\u2588\u2554\u2550\u2550\u2588\u2588\u2557\u2588\u2588\u2551\u2588\u2588\u2588\u2588\u2557  \u2588\u2588\u2551",
    " \u2588\u2588\u2588\u2588\u2588\u2588\u2554\u255d\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2551\u2588\u2588\u2551     \u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2551\u2588\u2588\u2551  \u2588\u2588\u2551\u2588\u2588\u2551\u2588\u2588\u2554\u2588\u2588\u2557 \u2588\u2588\u2551",
    " \u2588\u2588\u2554\u2550\u2550\u2550\u255d \u2588\u2588\u2554\u2550\u2550\u2588\u2588\u2551\u2588\u2588\u2551     \u2588\u2588\u2554\u2550\u2550\u2588\u2588\u2551\u2588\u2588\u2551  \u2588\u2588\u2551\u2588\u2588\u2551\u2588\u2588\u2551\u2514\u2588\u2588\u2557\u2588\u2588\u2551",
    " \u2588\u2588\u2551     \u2588\u2588\u2551  \u2588\u2588\u2551\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2557\u2588\u2588\u2551  \u2588\u2588\u2551\u2588\u2588\u2588\u2588\u2588\u2588\u2554\u255d\u2588\u2588\u2551\u2588\u2588\u2551 \u2514\u2588\u2588\u2588\u2588\u2551",
    " \u255a\u2550\u255d     \u255a\u2550\u255d  \u255a\u2550\u255d\u255a\u2550\u2550\u2550\u2550\u2550\u2550\u255d\u255a\u2550\u255d  \u255a\u2550\u255d\u255a\u2550\u2550\u2550\u2550\u2550\u255d \u255a\u2550\u255d\u255a\u2550\u255d  \u255a\u2550\u2550\u2550\u255d",
]

def print_banner():
    inner = _W() - 2
    sess  = load_session()
    sid   = sess.get("id", "")
    stat  = sess.get("status", "idle")
    proj  = sess.get("project", "")

    kiro_str = (f"{GR}\u2b24  kiro connected{R}" if KIRO_BIN
                else f"{RD}\u25cb  kiro not found{R}  {LGREY}\u2192 https://kiro.ai{R}")
    sc       = {"running": GR, "paused": YL, "failed": RD, "idle": LGREY}.get(stat, LGREY)
    sess_str = (f"{LGREY}session  {R}{CYB}{sid}{R}  {LGREY}{proj}  {R}{sc}\u25cf {stat}{R}"
                if sid else f"{LGREY}no session  \u00b7  type {R}{CY}start{R}{LGREY} to begin{R}")
    shortcuts = f"{DIM}/help \u00b7 /clear \u00b7 /session \u00b7 /model <name> \u00b7 exit{R}"

    print()
    print(_box_top(inner, title=f" {CYB}\u2b21 paladin{R} "))
    for ll in LOGO:
        print(_box_row(_center(f"{CY}{ll}{R}", inner - 2), inner))
    print(_box_row(_center(f"{DIM}AI Security Agent \u00b7 v{VERSION} \u00b7 powered by kiro{R}", inner - 2), inner))
    print(_box_sep(inner))
    print(_box_row(_center(kiro_str,  inner - 2), inner))
    print(_box_row(_center(sess_str,  inner - 2), inner))
    print(_box_sep(inner))
    print(_box_row(_center(shortcuts, inner - 2), inner))
    print(_box_bot(inner))
    print()

def print_help():
    sections = [
        ("Session", [
            ("init",          "Initialise paladin in current project"),
            ("start",         "Start a new agent session"),
            ("status",        "Show session status"),
            ("run [task]",    "Run any task via kiro (with full tool access)"),
        ]),
        ("Approvals", [
            ("approvals",     "List pending approvals"),
            ("approve <id>",  "Approve an action"),
            ("deny <id>",     "Deny an action"),
        ]),
        ("Activity & Policy", [
            ("activity [id]", "Show activity log"),
            ("policy list",   "List security policies"),
            ("policy add",    "Add a policy interactively"),
            ("policy test",   "Test a prompt against policies"),
        ]),
        ("Utilities", [
            ("config",        "Show / edit config"),
            ("doctor",        "Health check"),
            ("version",       "Version info"),
        ]),
        ("REPL shortcuts", [
            ("/help",         "Show this help"),
            ("/clear",        "Clear screen"),
            ("/session",      "Show session details"),
            ("/model <name>", "Switch model"),
            ("exit / Ctrl-C", "Quit"),
        ]),
    ]
    print()
    for group, items in sections:
        print(f"  {B}{GREY}{group}{R}")
        for cmd, desc in items:
            pad = max(1, 22 - len(cmd))
            print(f"    {CY}{cmd}{R}{' '*pad}{GREY}{desc}{R}")
        print()

# ─── Commands ─────────────────────────────────────────────────────────────────

def _ask_input(label: str, choices: list = None, default: str = "") -> str:
    sfx = f" [{'/'.join(choices)}]" if choices else (f" [{default}]" if default else "")
    try:    raw = input(f"\n  {label}{sfx}: ").strip()
    except (EOFError, KeyboardInterrupt): return default
    return raw or default

def cmd_init(model=None):
    cwd = Path.cwd()
    (cwd / ".paladin").write_text(json.dumps({
        "initialized_at": datetime.now().isoformat(), "project": cwd.name}, indent=2))
    _ok(f"Initialized paladin in {cwd}")
    ask_kiro(f"Paladin initialized in '{cwd.name}'. Acknowledge and list what you can monitor.", label="init", model=model)

def cmd_start(model=None):
    sid = f"SES-{int(datetime.now().timestamp())}"
    save_session({"id": sid, "started_at": datetime.now().isoformat(),
                  "status": "running", "project": Path.cwd().name})
    _ok(f"Session {CYB}{sid}{R} started")
    ask_kiro(f"New Paladin session {sid} started in '{Path.cwd().name}'. Greet the user and ask what they want to work on.", label="start", model=model)

def cmd_status(model=None):
    sess = load_session()
    if not sess: _warn("No active session. Run: start"); return
    print()
    _print_box("Session Status", [
        f"{GREY}{'id':<16}{R}{CY2}{sess.get('id','')}{R}",
        f"{GREY}{'project':<16}{R}{CY2}{sess.get('project','')}{R}",
        f"{GREY}{'started':<16}{R}{CY2}{sess.get('started_at','')}{R}",
        f"{GREY}{'status':<16}{R}{GR}{sess.get('status','')}{R}",
    ])
    ask_kiro(f"Summarize this session: {json.dumps(sess)}. Any pending actions?", label="status", model=model)

def cmd_run(task=None, model=None):
    if not task: task = _ask_input("Task to run")
    if not task: _err("No task provided."); return
    sess = load_session()
    ctx  = f"\n\nCurrent session: {json.dumps(sess)}" if sess else ""
    ask_kiro(task + ctx, label="run", model=model, trust=True)

def cmd_approvals(model=None):
    ask_kiro("List all pending Paladin approval requests with ID, tool, risk level, and description.", label="approvals", model=model)

def cmd_approve(aid, msg=None, model=None):
    ask_kiro(f"Approve Paladin action ID: {aid}.{' Note: '+msg if msg else ''} Confirm and proceed.", label=f"approve {aid}", model=model)

def cmd_deny(aid, msg=None, model=None):
    ask_kiro(f"Deny Paladin action ID: {aid}.{' Reason: '+msg if msg else ''} Confirm and explain.", label=f"deny {aid}", model=model)

def cmd_activity(sid=None, model=None):
    if sid:
        ask_kiro(f"Full activity log for session {sid}: tool calls, decisions, approvals in order.", label=f"activity {sid}", model=model)
    else:
        ask_kiro("Activity log for current session: tool calls, agent messages, shield decisions.", label="activity", model=model)

def cmd_policy_list(model=None):
    ask_kiro("List all Paladin security policies: name, action, threshold, enabled, description.", label="policy list", model=model)

def cmd_policy_add(model=None):
    name   = _ask_input("Policy name")
    desc   = _ask_input("Description")
    action = _ask_input("Action", choices=["allow","ask","block"], default="ask")
    thresh = _ask_input("Risk threshold (0-100)", default="50")
    pol    = {"name": name, "description": desc, "action": action,
              "threshold": int(thresh or 50), "enabled": True}
    ask_kiro(f"Add this policy: {json.dumps(pol)}. Confirm and explain when it triggers.", label="policy add", model=model)

def cmd_policy_test(model=None):
    ti = _ask_input("Prompt or tool to test")
    if not ti: _err("Nothing to test."); return
    ask_kiro(f'Test against all policies: "{ti}". Show matches, decision, risk score, reasoning.', label="policy test", model=model)

def cmd_config():
    cfg = load_config()
    print()
    _print_box("Config", [
        f"{GREY}{'file':<16}{R}{DIM}{CONFIG_FILE}{R}",
        *[f"{GREY}{k:<16}{R}{CY2}{v}{R}" if v is not None else f"{GREY}{k:<16}{R}{LGREY}not set{R}"
          for k, v in cfg.items()],
    ])
    try:
        if input("  Edit a value? (y/N): ").strip().lower() == "y":
            key = _ask_input("Key"); val = _ask_input(f"Value for {key}")
            cfg[key] = val; save_config(cfg); _ok(f"{key} = {val}")
    except (EOFError, KeyboardInterrupt): pass

def cmd_doctor():
    checks = [
        ("kiro-cli",      bool(KIRO_BIN),              KIRO_BIN or "not found -- https://kiro.ai"),
        ("python",        sys.version_info >= (3, 9),  platform.python_version()),
        ("rich",          HAS_RICH,                    "ok" if HAS_RICH else "pip install rich"),
        ("config dir",    CONFIG_DIR.exists(),          str(CONFIG_DIR)),
        (".paladin",      (Path.cwd()/".paladin").exists(),
                          "found" if (Path.cwd()/".paladin").exists() else "run: init"),
        ("agent config",  Path(AGENT_CONFIG).exists(),
                          "found" if Path(AGENT_CONFIG).exists() else "missing"),
    ]
    print()
    _print_box("paladin doctor", [
        f"  {GR if good else YL}{'v' if good else '!'}{R}  {B}{name:<20}{R}{GREY}{detail}{R}"
        for name, good, detail in checks
    ])

def cmd_version():
    print()
    _print_box("paladin version", [
        f"{GREY}{'version':<16}{R}{CYB}v{VERSION}{R}",
        f"{GREY}{'python':<16}{R}{CY2}{platform.python_version()}{R}",
        f"{GREY}{'platform':<16}{R}{CY2}{platform.system()} {platform.release()}{R}",
        f"{GREY}{'kiro':<16}{R}{(GR+KIRO_BIN+R) if KIRO_BIN else (RD+'not found'+R)}",
    ])

# ─── REPL slash commands ──────────────────────────────────────────────────────

def _handle_slash(line: str, model_ref: list):
    parts = line.strip().split()
    cmd   = parts[0].lower()

    if cmd in ("/exit", "/quit", "/q"):
        raise SystemExit(0)
    elif cmd == "/help":
        print_help()
    elif cmd == "/clear":
        os.system("clear"); print_banner()
    elif cmd == "/session":
        s = load_session()
        if not s: _warn("No active session."); return
        print()
        for k, v in s.items():
            print(f"  {GREY}{k:<18}{R}{CY2}{v}{R}")
        print()
    elif cmd == "/model":
        if len(parts) > 1:
            model_ref[0] = parts[1]
            cfg = load_config(); cfg["model"] = parts[1]; save_config(cfg)
            _ok(f"Model \u2192 {B}{parts[1]}{R}")
        else:
            _info(f"Model: {B}{model_ref[0] or 'default'}{R}")
    else:
        _err(f"Unknown slash command: {cmd}  (try /help)")

# ─── Dispatcher ───────────────────────────────────────────────────────────────

def _dispatch(args: list, model: str = None) -> bool:
    if not args: return False
    cmd, rest = args[0].lower(), args[1:]

    if   cmd == "init":      cmd_init(model)
    elif cmd == "start":     cmd_start(model)
    elif cmd == "status":    cmd_status(model)
    elif cmd == "run":       cmd_run(" ".join(rest) if rest else None, model)
    elif cmd == "approvals": cmd_approvals(model)
    elif cmd == "approve":
        if not rest: _err("Usage: approve <id> [message]")
        else:        cmd_approve(rest[0], " ".join(rest[1:]) or None, model)
    elif cmd == "deny":
        if not rest: _err("Usage: deny <id> [reason]")
        else:        cmd_deny(rest[0], " ".join(rest[1:]) or None, model)
    elif cmd == "activity":  cmd_activity(rest[0] if rest else None, model)
    elif cmd == "policy":
        sub = rest[0].lower() if rest else ""
        if   sub == "list": cmd_policy_list(model)
        elif sub == "add":  cmd_policy_add(model)
        elif sub == "test": cmd_policy_test(model)
        else: _err("Usage: policy [list|add|test]")
    elif cmd == "config":    cmd_config()
    elif cmd == "doctor":    cmd_doctor()
    elif cmd == "version":   cmd_version()
    elif cmd in ("help", "--help", "-h"): print_help()
    else: return False
    return True

# ─── Entry point ──────────────────────────────────────────────────────────────

def main():
    _mkdirs()
    bootstrap()

    args      = sys.argv[1:]
    cfg       = load_config()
    model_ref = [cfg.get("model")]

    if args:
        if not _dispatch(args, model_ref[0]):
            ask_kiro(" ".join(args), label="task", model=model_ref[0], trust=True)
        return

    print_banner()

    if not KIRO_BIN:
        _err("kiro-cli not found. Install from https://kiro.ai and run `kiro login`.")
        print()

    try:
        while True:
            try:
                sess = load_session()
                sid  = sess.get("id", "")
                tag  = f"#{sid[-5:]} " if sid else ""
                line = input(f"  {CY}\u2b21 {tag}\u276f {R}").strip()
            except EOFError:
                break
            except KeyboardInterrupt:
                print(); break

            if not line: continue
            if line.lower() in ("exit", "quit", "q"): break
            if line.startswith("/"):
                _handle_slash(line, model_ref); continue
            if not _dispatch(line.split(), model_ref[0]):
                ask_kiro(line, label="chat", model=model_ref[0], trust=True)

    except SystemExit:
        pass

    print(f"\n  {DIM}bye.{R}\n")

if __name__ == "__main__":
    main()
